[tool.poetry]
name = "abot"
version = "0.1.0"
description = ""
authors = ["djkcyl <cyl@cyllive.cn>"]

[tool.poetry.dependencies]
python = "^3.9"
graia-application-mirai = "^0.19.0"
graia-saya = "^0.0.9"
graia-scheduler = "^0.0.4"
requests = "^2.25.1"
Pillow = "^8.2.0"
numpy = "^1.20.3"
matplotlib = "^3.4.2"
wordcloud = "^1.8.1"
pkuseg = "^0.0.25"
dnspython = "^2.1.0"
moviepy = "^1.0.3"
pydantic = "1.7"
peewee = "^3.14.4"
PyMySQL = "^1.0.2"
PixivPy = "^3.5.11"
func-timeout = "^4.3.5"
graiax-silkcoder = "0.0.12"
httpx = "^0.18.2"
playwright = "^1.12.1"
lxml = "^4.6.3"
PyYAML = "^5.4.1"
interval = "^1.0.0"
tencentcloud-sdk-python = "^3.0.452"
xmltodict = "^0.12.0"
azure-cognitiveservices-speech = "^1.18.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
